### ISSUE TITLE
Refactor smoke tests and run them on CI

### ISSUE THREAD

**Issue by gromakovsky** [tz-wrapped/tezos-btc#123]
# Clarification and motivation

Running nettest scenarios requires some setup, e. g. `tezos-client` executable ought to be available. We have solved such a task in `morley`, see https://gitlab.com/morley-framework/morley/-/issues/203 and https://gitlab.com/morley-framework/morley/-/merge_requests/408. Now we should do it here as well.

Note that in this repo smoke tests are a bit different than in others:
1. They are part of the `tzbtc` executable which is a bit weird, because they are tests, so it's more natural to put them into a test-suite.
2. They also use `tzbtc-client` based implementation.
3. We also have bats tests which are essentially smoke tests as well. Currently we run them with `--dry-run`, but I suppose we can run them without `--dry-run` now because all infrastructure for that is now available.

# Acceptance criteria

1. Smoke tests are moved into a new test-suite.
2. In each MR CI runs Haskell smoke tests for nbit on local chain. Same for bats smoke tests (they should be run w/o `--dry-run`, probably it's better to run with AND without `--dry-run`).
3. CI should also run smoke tests on testnet (node address can be hardcoded and updated manually) regularly (e. g. once a day).
4. Smoke tests should be launched via integrational testing engine once (in only one test-suite). I don't know if we are doing it now.
5. If nightly CI run fails, tezos-alerts@serokell.io should be notified.

# Checklist

- [x] This issue description complies with the guidelines written [here](https://www.notion.so/serokell/Creating-an-issue-4c82edd3c2c74825ac2de63575ef3b18).

- [x] I have set the appropriate Type and State. If this issue implies making a PR not to the master branch, I have specified the branch

**Comment by rvem** [comment]
Apparently, there is no sense in keeping bats tests for `tzbtc-client`, because of two things:
1) They require setting up additional environment
2) Ported smoke tests will have part when the `tzbtc-client` is called for deploying and calling the contract

**Comment by gromakovsky** [comment]
Oh, I wrote in #134 that I think we should do #134 before #123, but I didn't write about that in #123. So yes, I think we should do #134 first, so that we use tasty integration with nettest and have only 1 test-suite. I haven't found an assignee for #134 yet, but you can work on #137 in the meantime.

**Comment by rvem** [comment]
Well, I plan to migrate smoke tests to tasty integration in scope of this issue if you don't mind
