### ISSUE TITLE
Switch to morley-nettest completely

### ISSUE THREAD

**Issue by Martoon-00** [tz-wrapped/tezos-btc#134]
# Clarification and motivation

This repository seems to contain the very first version of nettest, but now we have a more developed version of it within the morley repository. So we have to go away from our self-written code and use primitives from morley-nettest where possible.

# Acceptance criteria

* Manually written pieces of communication with tezos-client are removed in favour of morley-nettest primives.
* In a case where are pieces not present in morley-nettest, and they seem quite general, consider moving them to morley-nettest.

**Comment by gromakovsky** [comment]
There is also #123. I think we should do this issue first and then setup CI within #123.
