### ISSUE TITLE
Use auto-refilling addresses where necessary

### ISSUE THREAD

**Issue by pasqu4le** [tz-wrapped/tezos-btc#170]
# Clarification and motivation

Some network tests are currently failing because some addresses' account in them run out of funds, for example see [this pipeline](https://buildkite.com/serokell/tezos-btc/builds/661#5cb01790-335d-4d56-90e2-edb9ace58c8c).

However, after [morley/#638](https://gitlab.com/morley-framework/morley/-/issues/638), `cleveland` is now able to have addresses with auto-refilling balances, which are exactly meant to solve this problem,
 
# Acceptance criteria

Auto-refilling addresses are used to avoid "out of balance" failures in network tests.

**Comment by lierdakil** [comment]
Uhhh... are you sure the pipeline you liked didn't fail because the moneybag ran dry? Because it seems like that's exactly what happened...

**Comment by pasqu4le** [comment]
:thinking: you may be right, I restarted the job there (same pipeline), the funds you sent the address should be plenty, let's see how it goes.

**Comment by lierdakil** [comment]
That seems to have helped, but oof, I've thrown in 10ktz, and now it sits at 3.7ktz after two runs. Which means it eats about 3.2 ktz per run. I've thrown in some more, but at this rate it'll run out in less than a month.

**Comment by pasqu4le** [comment]
Yes, sadly it it quite expensive to run all those tests, perhaps it's time to reduce their frequency.

I added some more, but sadly I don't think that there's any way to automate the refilling of moneybags

Anyway the problem seemed to have been that, so I'm closing this issue.
